### ISSUE TITLE
Updater doesnt select the srcds window to input the warning text.

### ISSUE THREAD

**Issue by lithium720** [C0nw0nk/SteamCMD-AutoUpdate-Any-Gameserver#10]
Windows Server 2012 R2

What seems to happen is when there is a detected update, it fails to select the srcds window and sometimes selects stuff on the desktop and opens them.
I did not edit below your line, in fact I changed as little number of settings as i could to get it to work. This is for the non-curl version.

**Comment by C0nw0nk** [comment]
It is vbscript so it should open the srcds window or goto the srcds window and type into it using vbscripts send keys command.

"say Server is shutting down to install updates, Goodbye!"

**Comment by lithium720** [comment]
Right, and what I'm basically trying to say is that rather than doing that, it fails to select the srcds window and opens somthing random on the desktop and then starts typing. I had notepad open at one point, and it started typing stuff into the notepad like
"say Server is shutting down to install updates, Goodbye!"

Rather than typing it into the srcds window.

The script works for me otherwise though. It's odd and I cant figure out why its doing that

**Comment by C0nw0nk** [comment]
Do you run multiple servers concurrently ?

I did replicate it once but only when running multiple instances of srcds I was going to add a simple true false if check to allow people to disable the server shutting down for updates announcement. But due to the way the script works there is not going to be much of a way around it typing into the srcds window without diving into C++.

PS : If someone does come up with plain text solution to keep it in scripted format on command line just make a pull request and i will push it to the main branch.

**Comment by lithium720** [comment]
No I do not run multiple servers concurrently. Just one.
Yeah that's okay, I just cut out all of the notification stuff and it works great, I guess there just won't be any warning when the sever needs to update. _shrugs_

And maybe it has something to do with the fact that I manage my server Via RDP, I haven't tested it with anything other than RDP. I am aware that RDP does some weird ass shit, so I will try VNC I suppose.
